### ISSUE TITLE
Fail build if jekyll warns about layout

### ISSUE THREAD

**Issue by kmindi** [kmindi/CryptoExamples#9]
It occured, that contributors assumed all was fine with their contribution because the page could be built. But instead the page missed the layout. This was reflected in the build output with warnings, but no errors. 

We should add some build output check to fail the build if these kind of warnings occur. 

I don't know about other warnings that could be neglected.

**Comment by neglectable** [comment]
Could you please provide a link to a Travis build where this happened?

**Comment by kmindi** [comment]
e.g. this one: https://travis-ci.org/kmindi/CryptoExamples/builds/355242862?utm_source=github_status&utm_medium=notification
